### ISSUE TITLE
Create Vagrant development environment

### ISSUE THREAD

**Issue by mandy-cmd** [dev-ops-recommendation/recommendations#1]
**As a** developer, 
**I need** to set up vagrant environment and dependencies
**So that** I can have the team can work with the same Vagrant environment

**Assumptions**
- Vagrant is installed
- Python is installed (3.x)

**Acceptance Criteria**
```
Given a working Vagrantfile with proper dependencies needed for the project
When `vagrant up` and `vagrant ssh` is used
Then Vagrant is working properly
```

**Comment by procrasprincess** [comment]
This should be updated so it's using the story template

**Comment by mandy-cmd** [comment]
Handled as part of https://github.com/dev-ops-recommendation/recommendations/issues/21
