### ISSUE TITLE
Develop Update Endpoint

### ISSUE THREAD

**Issue by Aurora1024** [dev-ops-recommendation/recommendations#10]
As a developer
I need to update relationships as recommendations for user
So that the recommendations could be queried later to present to user.

Assumptions:

- enumeration of relationship/recommendation type is already defined.

- body will be { product-id-1: <>, product-id-2: <>, relationship:<> }

- Error will be thrown if relationship does not exist between product-1 and product-2

Acceptance Criteria:

`Given /recommendations resources and two product-ids with a existing relationship
When POST /recommendations with body in the assumptions
Then new relationship between product-id-1 and product-id-2 should be updated in the database   
and return the entity in the response. 

Given /recommendations resources and two product-ids that have no relationship defined
When POST /recommendations with body in the assumptions
An exception should be throws to prompt no relationship exist between the two products. 

Unit test coverage should be > 95%`

**Comment by mandy-cmd** [comment]
This could be modified and extended as Update endpoint while the relationship isn't necessarily alway be "go together"
