### ISSUE TITLE
Enumerate different recommendation types.

### ISSUE THREAD

**Issue by Aurora1024** [dev-ops-recommendation/recommendations#11]
As a Developer
I need to know the id of each recommendation types.
So that I can update product relation DB or recommend product based on each recommendation types.

Assumptions

Recommendation types and ID are as follows:
go together, 1
cross-sell, 2
up-sell, 3
accessory, 4

Acceptance Criteria
Given /recommendations/types
When GET /recommendations/types
Then I will get the recommendation types schema

**Comment by mandy-cmd** [comment]
This is done along with CREATE endpoint. Resolving.
