### ISSUE TITLE
Setup nosetests

### ISSUE THREAD

**Issue by zyy9871** [dev-ops-recommendation/recommendations#15]
**As a** Developer
**I need** nosetests work
**So that** I can type nosetests to test me code

**Assumptions:** 
* We will create a setup.cfg file with all nosetests options
* We will place test cases in a ./tests folder

**Acceptance Criteria:**
```
When run these tests using nosetest
Then I shall see them all green (passing)
```

**Comment by zyy9871** [comment]
According to Minimum Viable Product, we should divide this into smaller pieces. I'm afraid divide it into setup, model, Create, Read, Update, Delete, List, Query, Action, and test coverage is too much so I just leave it here. Can someone give advice?

**Comment by mandy-cmd** [comment]
I would suggest each person who develops the endpoint should also cover the corresponding the unit test. The actual code and testing could be written in the same story with test coverage as one of the acceptance criteria. 
This could be the main issue to track our progress and could be left as 0 point if we wish.

**Comment by mandy-cmd** [comment]
We should be able to close this since nosetests is already working along with Create nosetests.
