### ISSUE TITLE
Move Story Template to Directory .github/ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by procrasprincess** [dev-ops-recommendation/recommendations#2]
**As a** team member, 
**I need** to move the story_template.md to `/.github/ISSUE_TEMPLATE`
**So that** the story template will show up properly on github (which is not showing up currently)

**Assumptions**
- The team will use this template to create stories 

**Acceptance Criteria**
```
Given a story_template.md file under `/.github/ISSUE_TEMPLATE`
When creating a story
Then the story template is available to use in github
```

**Comment by mandy-cmd** [comment]
This is now resolved and template should be working as expected. Resolving.
