### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by zyy9871** [dev-ops-recommendation/recommendations#37]
**As a** developer
**I need** test cases run before Pull Request
**So that** master branch is always deployable

**Assumptions:** 
* Need to create a account on travis-ci.com to add GitHub Organization and repository to Travis CI
* Need to create a .travis.yml file to configure Travis CI
* Need to add a Travis CI badge to README.md file to visualize CI

**Acceptance Criteria:**
```
Given new branches
When creating pull requests
Then tests should run on Travis CI and badge should show in README.md
```

**Comment by mandy-cmd** [comment]
@procrasprincess Could you set up the code coverage check & badge as well?
