### ISSUE TITLE
Integrate Pull Requests with Slack Channel

### ISSUE THREAD

**Issue by procrasprincess** [dev-ops-recommendation/recommendations#38]
**As a** developer
**I need** to integrate pull requests with team slack channel
**So that** the team will be notified automatically with pull requests, prompting team feedback in a timely manner

**Assumptions:** 
* Integrate pull requests with team slack channel #recommendations 

**Acceptance Criteria:**
```
Given team channel
When a developer makes a pull request in the repo
Then a notification will be automatically generated in the team slack channel
```

**Comment by mandy-cmd** [comment]
Configured on slack.github.com. Next step is testing. Putting in review.
