### ISSUE TITLE
Get Database Credentials

### ISSUE THREAD

**Issue by procrasprincess** [dev-ops-recommendation/recommendations#44]
**As a** developer
**I need** to modify team's service to get the database credentials  
**So that** the service runs correctly

**Assumptions:** 
* use `DATABASE_URI` for 3rd party database like PostgreSQL (from ElephantSQL.com)
* example: `models.py` in `lab-bluemix-cf`

**Acceptance Criteria:**
```
Given modifications
When the service is running
Then the service can access (read/write) team's PostgresSQL database
```

**Comment by mandy-cmd** [comment]
URL postgres://vxbugyke:ht0RbVauOekmn1z-VsriWk94gmD9hMA_@chunee.db.elephantsql.com/vxbugyke
