### ISSUE TITLE
Setup .gitignore File

### ISSUE THREAD

**Issue by procrasprincess** [dev-ops-recommendation/recommendations#5]
**As a** developer, 
**I need** to set up and configure the `.gitignore` file
**So that** some unwanted files are ignored in the version control

**Assumptions**
- Existing `.gitignore` file
- Some unwanted files are displayed
- Refer to [gitignore Documentation](https://git-scm.com/docs/gitignore) if needed

**Acceptance Criteria**
```
Given an existing `.gitignore` file with changes such as `.vagrant`
When in version control
Then some unwanted files are ignored
```

**Comment by zyy9871** [comment]
We have it when merge with template so I think we can finish this.

**Comment by procrasprincess** [comment]
Changes have already been made when merging.
