### ISSUE TITLE
Add a Production Deploy Stage to the pipeline

### ISSUE THREAD

**Issue by Aurora1024** [dev-ops-recommendation/recommendations#58]
**As a developer** ...  
**I need add a Production Deploy Stage to the pipeline** ...  
**So that I can deploy to the production space** ...  

**Assumptions:** 
* Create a new Space in your Cloud Foundry account called: prod
* all of the integration tests pass

**Acceptance Criteria:**
```
Given Continuous Delivery Pipeline in IBM Cloud...
When deploy to the production space...
Then it should go pass Production Deploy Stage...
```

**Comment by mandy-cmd** [comment]
Test stage added and all tests passing now.
