### ISSUE TITLE
Picking the correct DB

### ISSUE THREAD

**Issue by vg2134** [dev-ops-recommendation/recommendations#6]
As a Developer
I need to pick the appropriate database
So that I can store customer's account information

**Assumptions**

First Name
Last Name
Customer_Id (as key, generated by system so it's always unique from each other)
User_Id
Password
Address

**Acceptance Criteria**
Given all of the following fields except customer id in the Assumptions are provided
When I call the Rest APIs except /.
Then database should respond correctly.

**Comment by mandy-cmd** [comment]
We decided on postgres. Resolving.
